name = "ohno-template"
compatibility_date = "2024-04-05"
pages_build_output_dir="./dist"

[placement]
mode = "smart"

[vars]
OPENAI_API_KEY = ""
ACCOUNT = ""
USER_NAME = ""
PASSWORD = ""
ROLE = ""
DATABASE = ""
SCHEMA = ""
WAREHOUSE = ""
SNOWFLAKE_API_URL = ""
TOKEN = ""